### ISSUE TITLE
deploy jobを追加

### ISSUE THREAD

**Issue by gn5r** [gn5r/todo-app#1]
GitHub Pagesにデプロイするjobを追加する
デプロイトリガーは下記ターゲットブランチのpush
[vue-confirm](https://github.com/gn5r/vue-confirm/blob/main/.github/workflows/deploy.yml)の設定を流用

- ターゲットブランチ
  - main
  - dev

**Comment by gn5r** [comment]
Upload artifactsにて成果物(dist)へのパス指定が必須

```
- name: Upload artifacts
  uses: actions/upload-pages-artifact@v3
  with:
    path: ./dist
```
